### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Wanderson77** [MarceloPrado/flash-calendar#10]
Hi Marcelo, is there any way I can contribute to this project. To begin with, it could be documentation. Thanks

**Comment by MarceloPrado** [comment]
Hi @Wanderson77! I don't have anything in mind yet, but if you have ideas on how the existing docs could be better, I'd be happy to listen 🙂

**Comment by menadeth** [comment]
Does Flash Calendar support the functionality for multiple date selections directly, aside from using date ranges? I'm looking for a way to allow users to select individual, non-consecutive dates. If this feature isn't currently supported, are there any recommended workarounds or plans to include it in future updates?

**Comment by MarceloPrado** [comment]
Closing this since it's a no-op.
