### ISSUE TITLE
Bug: calendarActiveDateRanges disappearing

### ISSUE THREAD

**Issue by DrZoidberg09** [MarceloPrado/flash-calendar#11]
Hi Marcelo,

First of all, thank you for this great piece of work! I was long time looking for a calendar based on flash-list.

Here is the issue:

If you scroll past the calendarActiveDateRanges for a few months and then scroll back, they are gone. e.g. events in January are gone if you scroll to June, February to July, and so on.

Thank you so much!

**Comment by MarceloPrado** [comment]
Hi @DrZoidberg09, thanks for reporting! Do you have a minimal code example I could use to repro this issue? Something like the ones provided by the docs ([example](https://marceloprado.github.io/flash-calendar/fundamentals/tips-and-tricks#programmatically-scrolling-to-a-date)) that I can copy/paste from my side 🙂

**Comment by MarceloPrado** [comment]
Thanks for the report - fix available in the latest [0.0.6](https://github.com/MarceloPrado/flash-calendar/releases/tag/%40marceloterreiro%2Fflash-calendar%400.0.6) release.

**Comment by DrZoidberg09** [comment]
https://github.com/MarceloPrado/flash-calendar/assets/96449693/128f39c9-eb1e-4e21-862f-38709aebc91f

@MarceloPrado Could you please have another look? It still acts like this. Thank you so much!

**Comment by Marcosld** [comment]
Was this fixed in the end?
