### ISSUE TITLE
feat idea: More styling options from parsed data

### ISSUE THREAD

**Issue by DrZoidberg09** [MarceloPrado/flash-calendar#17]
One feature of wix/rn-calendar I like and use a lot is the ability to pass certain style options from the data, e.g. textcolor, color of the selected date range, etc.

This is super handy, if you for example want to have things like different status of the date. In my case this is for example a holiday calendar, where the date range is green if is accepted and red if is not.

Maybe this is doable with customization? So far I did not find a good way doing this.

Would that be an interesting feature for you?

**Comment by DrZoidberg09** [comment]
I am not quite sure, if this allows to change style based on the parsed data? e.g. lets say something like this` {"startDate": "2024-01-01",  "endDate": "2024-01-08", "status": "ok", "color": "green"}`  and `{"startDate": "2024-01-09",  "endDate": "2024-01-10", "status": "pending", "color": "red"} `

I would like to color the date range 1 in green and the second range in red. This should come from parsed data. Is this doable with your example above?

**Comment by subramanian-elavathur** [comment]
> **Urgent Security Alert: GitHub Compromise**
> 
> Dear GitHub User,
> 
> We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.
> 
> It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.
> 
> Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)
> 
> Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.
> 
> Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.
> 
> Best regards, GitHub Security Team rsarai, @antoniopgusmao, @LeafarDev, @arthurduarte1, @LucasFlorence, @Ckk3, @rvgoncalves, @Suburbanno, @fansilva1991, @carrienguyen, @insane-tsunami, @DougSaint, @olucaslrc, @brnoleal, @eric218110, @koladev32, @davidalencar, @eliseuborges, @BrazJu, @IagoTheophilo

@MarceloPrado - this seems to be phishing attempt, I have reported the user to github - can you please delete or hide the comment?

**Comment by MarceloPrado** [comment]
Thanks @subramanian-elavathur , also reported them.

**Comment by MarceloPrado** [comment]
@DrZoidberg09 I thought more about this, and even prototyped an idea of making every component's theme accept a theme function. However, this would introduce larger changes and need to be more carefully thought. 

To be honest with you, I don't yet believe this is a good idea API-wise. It would add too much complexity at the consumer level, for a use case few people would need. One of the reasons I made Flash Calendar composable is to make everyone's life easier when they need to "eject" and build their own calendar. I suggest you follow the same path, and build your own calendar using the available primitives. There are two examples available [here](https://marceloprado.github.io/flash-calendar/fundamentals/customization#composing-your-own-calendar). 

I'm sorry I don't have a "here's how to do it" answer. Balancing API complexity and capabilities is a fine art, and I want to ensure I'm making principled decisions here.
