### ISSUE TITLE
add ability to mark some days on the calendar 

### ISSUE THREAD

**Issue by karam1ashqar** [MarceloPrado/flash-calendar#34]
can be called `calendarMarkedDateIds` and DayState of "**marked**" and behave like the current `calendarDisabledDateIds` and "**disabled**" DayState

**Comment by MarceloPrado** [comment]
For now, I'm afraid I won't build this feature - it goes against the first [principle](https://marceloprado.github.io/flash-calendar/fundamentals/principles#solve-fewer-needs-better): **Solve fewer needs better**.

Adding marked day support adds new considerations such as:
* What's the difference between a marked and an active day?
* Can a day be both marked and active? How is that represented?

For this feature, I'd suggest you to compose your own calendar as recommended by the docs [here](https://marceloprado.github.io/flash-calendar/fundamentals/customization#composing-your-own-calendar) 🙂
