### ISSUE TITLE
Is there any way i can run a function on select disabled dates?

### ISSUE THREAD

**Issue by ivanyufen** [MarceloPrado/flash-calendar#38]
Is there any way i can run a function on select disabled dates? i need to show some alert when user click outside the allowed dates. Can i do this? thanks a lot :)

**Comment by MarceloPrado** [comment]
Hi @ivanyufen 
Check out #42 for an example on how to achieve this:
https://github.com/MarceloPrado/flash-calendar/assets/8047841/f2947294-4a52-4add-bff9-4f238f16f3c1
