### ISSUE TITLE
Calendar.List example does not work

### ISSUE THREAD

**Issue by KaisAhmad** [MarceloPrado/flash-calendar#39]
Hi,

I am trying to implement Calendar.List in my app using the example on the marceloprado.github.io website but I receive a render error. The error indicates: "requireNativeComponent:AutoLayoutView was not found in the UIManager". Am I doing something wrong or is there a bug in the latest version? I am using the expo-dev client.

Package versions:
"expo": "~50.0.14"
"@marceloterreiro/flash-calendar": "^0.0.9"
"react": "18.2.0",
"react-native": "0.73.6",

![screenshot](https://github.com/MarceloPrado/flash-calendar/assets/8378087/a429fe6c-f54c-44c3-9c04-05d6dc7fb34a)

**Comment by MarceloPrado** [comment]
HI! Make sure you've followed the Installation guides [here](https://marceloprado.github.io/flash-calendar/#installation). You also need Flash List installed.
