### ISSUE TITLE
How can I create CALENDAR with dot mark

### ISSUE THREAD

**Issue by quangtuan28200** [MarceloPrado/flash-calendar#53]
I want to create a calendar with a dot mark like this, I tried but it does not optimize, any helps and thanks

![image](https://github.com/user-attachments/assets/9ae63510-b94b-46cb-9cc2-34c3de1f2d4e)
![image](https://github.com/user-attachments/assets/56486fb4-5297-47c7-8d8a-bda70d777b98)

**Comment by inthisar-hamza** [comment]
@quangtuan28200 can you provide full code as a text?
