### ISSUE TITLE
feat(text): Ability to pass TextProps to better control the <Text> days and weekdays

### ISSUE THREAD

**Issue by theonetheycallneo** [MarceloPrado/flash-calendar#61]
Being able to control accessibility with TextProps like allowFontScaling={false} or maxFontSizeMultiplier.

Here's my first minimal effort stab at it:
https://github.com/MarceloPrado/flash-calendar/pull/62

**Comment by MarceloPrado** [comment]
Thanks for the contribution! Besides my feedback on #62, it would be great to extend the documentation and showcase this new capability.
