### ISSUE TITLE
Calendar List fetch data current month

### ISSUE THREAD

**Issue by renatomserra** [MarceloPrado/flash-calendar#65]
Hello,

Thanks so much for this lib!
Using Calendar.List, how do i know the current visible month so i can fetch the correct data?
I come from the wix lib but it had really bad performance, tho this was supported there

**Comment by MarceloPrado** [comment]
Hi @renatomserra, thanks for the feedback 😄
Pushed a new documentation resource for that: https://marceloprado.github.io/flash-calendar/fundamentals/tips-and-tricks#listening-to-the-visible-months

Let me know if it helps
