### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by hugoh59** [MarceloPrado/flash-calendar#75]
This link is broken, where should we start? https://github.com/MarceloPrado/flash-calendar/blob/main/fundamentals/principles

**Comment by MarceloPrado** [comment]
Doesn't seem broken to me. Can you clarify?

https://github.com/user-attachments/assets/f4d40599-2a06-4d31-a504-98aba345fbaa

**Comment by hugoh59** [comment]
Somehow I've stumbled upon a button that led me here yesterday <img width="1792" alt="Capture d’écran 2024-12-14 à 10 16 35" src="https://github.com/user-attachments/assets/6366264a-063c-48f3-aa71-68481dee81ac" />
